--SET LONG 999999 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON
--COLUMN DDL FORMAT A1000
--
--BEGIN
--   DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
--   DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
--END;
--/

SET PAGESIZE 0
SET LINESIZE 200
SET LONG 2000
SET FEEDBACK OFF
SET HEADING OFF
SET ECHO OFF



SELECT 'GRANT SELECT ON ' || owner || '.' || table_name || ' TO ' || grantee || ';'
FROM dba_tab_privs
WHERE grantee = UPPER('RDWMS17SAL')
  AND privilege = 'SELECT'
ORDER BY owner, table_name;